### ISSUE TITLE
Double / Triple Post by RUN-GET Bot

### ISSUE THREAD

**Issue by BenjeeSR** [slashinfty/run-get#6]
Since yesterday, the RUN GET Discord Bot in the Wario Speedrun Community tends to double or triple send verified PBs.

![image](https://user-images.githubusercontent.com/69769854/90343283-5695a380-e00f-11ea-8c37-455269de53da.png)
![image](https://user-images.githubusercontent.com/69769854/90343278-4aa9e180-e00f-11ea-9136-e3bd29276734.png)

**Comment by slashinfty** [comment]
SRC's API has been sending back inconsistent results for the same query minutes apart, which resulted in duplicate posts. I believe [last night's commit](https://github.com/slashinfty/run-get/commit/7011c9c7e882a6d16e3dc8177096965a19787e9b) should address this.
